@startuml TiendaHamburgesas

class Pan{
Tipo:list
}
class Verduras{
Tipo:list
}
class Queso{
Tipo:list
}
class Salsa{
Tipo:list
}

class Hamburguesa{
Hamburguesa(str)
Precio(float)
}

class Carne{
Tipo:list
}

class Bebida{
tipo:list
}

class User{
Direccion:str
id:int
Metodo Pago:
Pedido(str)
Balance Total(float)
}

Hamburguesa <|-- Carne
Hamburguesa <|-- Queso
Hamburguesa <|-- Verduras
Hamburguesa <|-- Pan
Hamburguesa <|-- Salsa
@enduml 
